on: 
  workflow_dispatch

jobs:
  update-images:
    name: Fetch latest images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download images
        run: python main.py

      - name: Check changes
          id: check-changes
          uses: mskri/check-uncommitted-changes-action@v1.0.1

      - name: Commit changes
          if: steps.check-changes.outputs.changes != ''
          run: echo "There are uncommitted changes"