on: 
  workflow_dispatch

jobs:
  update-images:
    name: Fetch latest images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download images
        run: python main.py

      - name: Check changes
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo "tree is clean"
          else
            echo "tree is dirty, please commit changes before running this"