on: 
  workflow_dispatch

jobs:
  update-images:
    name: Fetch latest images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download images
        run: python main.py

      - name: Get changes
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'stats.json'
            prop_path: 'changed_images'

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated ${{steps.version.outputs.prop}} images
          file_pattern: brands/logos/*