on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download latest list
        run: python main.py

      - name: Download images
        run: python images.py

      - name: Download Product Overviews
        run: python products.py

      - name: Download Products
        run: python product.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated files
          default_author: github_actions

  update-website:
  name: Generate website
  runs-on: ubuntu-latest
  needs: update-data
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate website
      run: python website.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: Updated website
        default_author: github_actions

  release-daily:
    name: Generate release
    runs-on: ubuntu-latest
    needs: update-website
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "daily"
          message: "Daily release"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')