on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lists:
    name: Fetch latest lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download latest list
        run: python main.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated lists

  update-images:
    name: Fetch latest images
    needs: update-lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download images
        run: python images.py

      - name: Get changes
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'stats.json'
          prefix: stat

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated ${{ env.stat_changed_images }} images

  update-products:
    name: Fetch latest products
    needs: update-lists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download Products
        run: python products.py

      - name: Get changes
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'stats.json'
          prefix: stat

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated ${{ env.stat_changed_products }} product lists

  update-product:
    name: Fetch latest product
    needs: update-products
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download Products
        run: python product.py

      - name: Get changes
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: 'stats.json'
          prefix: stat

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: Updated ${{ env.stat_changed_product }} products