on: 
  workflow_dispatch:

jobs:
  release-daily:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1