on: 
  workflow_dispatch:

jobs:
  release-daily:
    name: Generate Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "daily"
          message: "Daily release"

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')